bind = '127.0.0.1:8082'
debug = true
access_log_format = '%(s)s | "%(R)s" |  Size: %(b)s | Referrer: "%(f)s"'
workers = 1
accesslog = '../.logs/hypercorn.access'
errorlog = '../.logs/hypercorn.error'
logconfig = 'json:../.config/logging.json'